version: '3.4'

services:
  backend:
    build:
      context: .
      target: ${BACKEND_ENV}
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - APP
    image: ${DOCKER_USERNAME}/${DC_PREFIX}-backend${DC_POSTFIX}:${APP_VERSION}
    container_name: ${DC_PREFIX}-backend${DC_POSTFIX}
    environment:
      - http_proxy
      - https_proxy
      - aws_access_key_id
      - aws_secret_access_key
      - BACKEND_PORT
      - ES_THREADS
      - ES_MAX_TRIES
      - ES_CHUNK
    volumes:
      - ${PROJECTS}:/${APP}/projects/
      - ${BACKEND}/log:/${APP}/log/
      - ${UPLOAD}:/${APP}/upload/
      - ${MODELS}:/${APP}/models/
      - ${FRONTEND}/matchIdConfig:/${APP}/matchIdConfig/
    restart: always

networks:
  default:
    external:
      name: ${DC_NETWORK}
