version: '2'

# this docker configuation is for dev use only
# it is supposed that your declared some ENV variables:
#   - ${FRONTEND} points to matchID-frontend (from GitHub, branch 'master')
#   - ${PROJECTS} points to your projects path
#   - ${UPLOAD} points to your upload path
# the dev conf allows you to change both python and nodejs code and conf live they will be
# updated within the docker instances

# for dev use it is recommanded to have at least 8Gb of memory and SSD and 4 vCPU, to ensure
# good performance and testing.

# for production use many adaptation will be needed if you use docker
# - assume you docker images with a custum managed repo
# - securize nginx routes allowing only stricly needed routes of API
# - build the static files from node frontend and put them to the nginx
# - build a cluster for elasticsearch
# - use real volumes : S3-like storage for configurations (using volumes) of front and back,
#   and DB-storage for ES volume like SSD volumes (or memory storage still better)

services:
  nginx-dev:
    image: nginx
    container_name: matchid-nginx-dev
    depends_on:
      - frontend-dev
    volumes:
      - ${BACKEND}/nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    restart: always

  frontend-dev:
    build:
      context: ${FRONTEND}
      dockerfile: Dockerfile.dev
      args:
        proxy: ${http_proxy}
    image: matchid-frontend-dev:latest
    container_name: matchid-frontend-dev
    volumes:
      - ${FRONTEND}/index.html:/matchid/index.html
      - ${FRONTEND}/.babelrc:/matchid/.babelrc
      - ${FRONTEND}/.editorconfig:/matchid/.editorconfig
      - ${FRONTEND}/.eslintignore:/matchid/.eslintignore
      - ${FRONTEND}/.eslintrc.js:/matchid/.eslintrc.js
      - ${FRONTEND}/matchIdConfig:/matchid/matchIdConfig/
      - ${FRONTEND}/config:/matchid/config/
      - ${FRONTEND}/src:/matchid/src/
      - ${FRONTEND}/build:/matchid/build/

networks:
  default:
    external:
      name: matchid
 
